name: wipac ci/cd

on: [ push ]

env:
  PYTHON_VERSION: '3.12'  # NOTE: update, someday

jobs:

  #############################################################################
  # LINTERS
  #############################################################################

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: WIPACrepo/wipac-dev-flake8-action@v1.2

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: WIPACrepo/wipac-dev-mypy-action@v2.0
